### ISSUE TITLE
error while compiling complex version with intel fortran

### ISSUE THREAD

**Issue by DdeRosa** [nasa/CFL3D#26] opened 2020-03-26 16:05 UTC
OS: Red Hat Enterprise
Fortran: Intel(R) Parallel Studio XE 2018 Update 2

Complex libraries compile without issues, but both sequential and mpi versions provide the following error

> mpiifort -DDIST_MPI -DDBLE_PRECSN -DP3D_SINGLE -DLINUX -DINTEL -DNOREDIRECT -DCGNS -DDBLE_PRECSN -I/u1/dedo532/EXPORT/CGNS_BIN/include -DCMPLX -z muldefs -xHost -traceback -fpe0 -o cfl3dcmplx_mpi ccomplex.o development.o main.o \
libdist.a libcommon.a -L/u1/dedo532/EXPORT/CGNS_BIN/include/LINUX64   -lcgns

**libcommon.a(bc1001.o): In function `bc1001_':
bc1001.F:(.text+0x4b10): undefined reference to `erf_'**

**Comment by ericzhng** [comment] 2021-03-03 05:17
Me too. Did you solve this issue?

**Comment by DdeRosa** [comment] 2021-03-03 08:26
Hi, unfortunately since I have been in lockdown I had no many opportunities to work on this topic, also due to lack of PhD students.
Hoping to work again on it as soon as possible.

**Comment by mskim0401** [comment] 2021-04-20 03:08
I found what was problem. The problem is that Fortran error function cannot read imaginary values.

I did it following step
1. See bc1001.F file from CFL3D/source/cfl3d/libs/
2. In line 386, what you have to do is to add 'real' command to 'erf'
- Existing code
     +    vtp*(0.5*(1.-erf(((xxx-xerf)/sigerf))))*xmach

- Modified code
     +    vtp*(0.5*(1.-erf(real(((xxx-xerf)/sigerf)))))*xmach

However, I'm not sure bc1001 works well. I just solved compilation error.
I used Intel oneapi 2021.2.0 package
Good luck.

**Comment by crumsey** [comment] 2021-04-28 22:21
Fixed on 4/28/2021

**Closed as completed by crumsey** 2021-04-28 22:21 UTC
